// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9j6tUz6jS9fy0tTRdzxFJJG47DGGrq6k',
    appId: '1:551301821386:web:182f9b39afbf28c40b9533',
    messagingSenderId: '551301821386',
    projectId: 'laza-e-commerce-d3ca0',
    authDomain: 'laza-e-commerce-d3ca0.firebaseapp.com',
    storageBucket: 'laza-e-commerce-d3ca0.appspot.com',
    measurementId: 'G-WC7PT1M2QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE7jnflyGA0KxM6-rlWjsThlLAkOEcDuo',
    appId: '1:551301821386:android:a4669e9fa7df3c470b9533',
    messagingSenderId: '551301821386',
    projectId: 'laza-e-commerce-d3ca0',
    storageBucket: 'laza-e-commerce-d3ca0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRvty8RIxfKs1KXhoJo5xImSnPVfn0NVM',
    appId: '1:551301821386:ios:89ca01277f7738890b9533',
    messagingSenderId: '551301821386',
    projectId: 'laza-e-commerce-d3ca0',
    storageBucket: 'laza-e-commerce-d3ca0.appspot.com',
    iosBundleId: 'com.example.laza',
  );
}
